name: CI/CD Pipeline - Product Trend Tracker

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: product-trend-tracker
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/product-trend-tracker

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies and run tests
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest -v || exit 1

      # Step 4: Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build and push Docker image
      - name: Build and push image
        id: docker_build
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t $DOCKERHUB_REPO:$IMAGE_TAG -t $DOCKERHUB_REPO:latest .
          docker push $DOCKERHUB_REPO:$IMAGE_TAG
          docker push $DOCKERHUB_REPO:latest
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $DOCKERHUB_REPO:$IMAGE_TAG)
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_ENV

      # Step 6: Deploy to cloud (Render or AWS)
      - name: Deploy to Render (example)
        if: ${{ success() }}
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.CLOUD_DEPLOY_TOKEN }}" \
            -d '{"serviceId": "srv-abc123", "clearCache": true}' \
            https://api.render.com/v1/services/srv-abc123/deploys

      # Step 7: Deployment summary
      - name: Write deployment summary
        run: |
          echo "### ✅ Product Trend Tracker Deployed Successfully 🚀" >> $GITHUB_STEP_SUMMARY
          echo "- **Image Tag:** $IMAGE_NAME:${{ env.image_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Digest:** ${{ steps.docker_build.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployment URL:** [${{ secrets.CLOUD_DEPLOY_URL }}](${{ secrets.CLOUD_DEPLOY_URL }})" >> $GITHUB_STEP_SUMMARY
